import "../styles/globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { AppProvider } from "./context/context";
import { Footer, Modal, Navbar } from "./components";

export const metadata = {
  title: "OpenTable Clone",
  description:
    "Generated by create next app, OpenTable clone, created by NBojan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <main className="containerBoot m-auto">
            <Navbar />
            <Modal />
            {children}
            <Footer />
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
